name: "Build flake example"
on:
  pull_request:
  push:
jobs:
  nix:
    name: ${{matrix.version}} on ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [0.8.4, 0.9.2, 0.10.101]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - run: cd examples/ci && nix build '.#"${{matrix.version}}"' --show-trace
